services:
  postgres:
    container_name: postgres-sql-szt
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: szteam_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-szt
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  szt-api:
    container_name: szt-api
    image: szt/szt:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  szt-frontend:
    container_name: szt-frontend
    image: szt/szt-frontend:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - szt-api

networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local