/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approveReturnBorrowGame } from '../fn/game/approve-return-borrow-game';
import { ApproveReturnBorrowGame$Params } from '../fn/game/approve-return-borrow-game';
import { borrowGame } from '../fn/game/borrow-game';
import { BorrowGame$Params } from '../fn/game/borrow-game';
import { findAllBorrowedGames } from '../fn/game/find-all-borrowed-games';
import { FindAllBorrowedGames$Params } from '../fn/game/find-all-borrowed-games';
import { findAllGames } from '../fn/game/find-all-games';
import { FindAllGames$Params } from '../fn/game/find-all-games';
import { findAllGamesByOwner } from '../fn/game/find-all-games-by-owner';
import { FindAllGamesByOwner$Params } from '../fn/game/find-all-games-by-owner';
import { findAllReturnedGames } from '../fn/game/find-all-returned-games';
import { FindAllReturnedGames$Params } from '../fn/game/find-all-returned-games';
import { findGameById } from '../fn/game/find-game-by-id';
import { FindGameById$Params } from '../fn/game/find-game-by-id';
import { GameResponse } from '../models/game-response';
import { PageResponseBorrowedGameResponse } from '../models/page-response-borrowed-game-response';
import { PageResponseGameResponse } from '../models/page-response-game-response';
import { returnBorrowGame } from '../fn/game/return-borrow-game';
import { ReturnBorrowGame$Params } from '../fn/game/return-borrow-game';
import { saveGame } from '../fn/game/save-game';
import { SaveGame$Params } from '../fn/game/save-game';
import { updateArchivedStatus } from '../fn/game/update-archived-status';
import { UpdateArchivedStatus$Params } from '../fn/game/update-archived-status';
import { updateSharableStatus } from '../fn/game/update-sharable-status';
import { UpdateSharableStatus$Params } from '../fn/game/update-sharable-status';
import { uploadGameCoverPicture } from '../fn/game/upload-game-cover-picture';
import { UploadGameCoverPicture$Params } from '../fn/game/upload-game-cover-picture';

@Injectable({ providedIn: 'root' })
export class GameService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllGames()` */
  static readonly FindAllGamesPath = '/games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames$Response(params?: FindAllGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return findAllGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames(params?: FindAllGames$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.findAllGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

  /** Path part for operation `saveGame()` */
  static readonly SaveGamePath = '/games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveGame()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveGame$Response(params: SaveGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveGame$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveGame(params: SaveGame$Params, context?: HttpContext): Observable<number> {
    return this.saveGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `uploadGameCoverPicture()` */
  static readonly UploadGameCoverPicturePath = '/games/cover/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadGameCoverPicture()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameCoverPicture$Response(params: UploadGameCoverPicture$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadGameCoverPicture(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadGameCoverPicture$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameCoverPicture(params: UploadGameCoverPicture$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadGameCoverPicture$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `borrowGame()` */
  static readonly BorrowGamePath = '/games/borrow/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `borrowGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  borrowGame$Response(params: BorrowGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return borrowGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `borrowGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  borrowGame(params: BorrowGame$Params, context?: HttpContext): Observable<number> {
    return this.borrowGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateSharableStatus()` */
  static readonly UpdateSharableStatusPath = '/games/shareable/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSharableStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateSharableStatus$Response(params?: UpdateSharableStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateSharableStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSharableStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateSharableStatus(params?: UpdateSharableStatus$Params, context?: HttpContext): Observable<number> {
    return this.updateSharableStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `returnBorrowGame()` */
  static readonly ReturnBorrowGamePath = '/games/borrow/return/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `returnBorrowGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnBorrowGame$Response(params: ReturnBorrowGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return returnBorrowGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `returnBorrowGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnBorrowGame(params: ReturnBorrowGame$Params, context?: HttpContext): Observable<number> {
    return this.returnBorrowGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `approveReturnBorrowGame()` */
  static readonly ApproveReturnBorrowGamePath = '/games/borrow/return/approve/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveReturnBorrowGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnBorrowGame$Response(params: ApproveReturnBorrowGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return approveReturnBorrowGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveReturnBorrowGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnBorrowGame(params: ApproveReturnBorrowGame$Params, context?: HttpContext): Observable<number> {
    return this.approveReturnBorrowGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateArchivedStatus()` */
  static readonly UpdateArchivedStatusPath = '/games/archived/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateArchivedStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateArchivedStatus$Response(params?: UpdateArchivedStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateArchivedStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateArchivedStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateArchivedStatus(params?: UpdateArchivedStatus$Params, context?: HttpContext): Observable<number> {
    return this.updateArchivedStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findGameById()` */
  static readonly FindGameByIdPath = '/games/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findGameById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findGameById$Response(params?: FindGameById$Params, context?: HttpContext): Observable<StrictHttpResponse<GameResponse>> {
    return findGameById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findGameById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findGameById(params?: FindGameById$Params, context?: HttpContext): Observable<GameResponse> {
    return this.findGameById$Response(params, context).pipe(
      map((r: StrictHttpResponse<GameResponse>): GameResponse => r.body)
    );
  }

  /** Path part for operation `findAllReturnedGames()` */
  static readonly FindAllReturnedGamesPath = '/games/returned';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllReturnedGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedGames$Response(params?: FindAllReturnedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBorrowedGameResponse>> {
    return findAllReturnedGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllReturnedGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedGames(params?: FindAllReturnedGames$Params, context?: HttpContext): Observable<PageResponseBorrowedGameResponse> {
    return this.findAllReturnedGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBorrowedGameResponse>): PageResponseBorrowedGameResponse => r.body)
    );
  }

  /** Path part for operation `findAllGamesByOwner()` */
  static readonly FindAllGamesByOwnerPath = '/games/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllGamesByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGamesByOwner$Response(params?: FindAllGamesByOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return findAllGamesByOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllGamesByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGamesByOwner(params?: FindAllGamesByOwner$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.findAllGamesByOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

  /** Path part for operation `findAllBorrowedGames()` */
  static readonly FindAllBorrowedGamesPath = '/games/borrowed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBorrowedGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBorrowedGames$Response(params?: FindAllBorrowedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBorrowedGameResponse>> {
    return findAllBorrowedGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBorrowedGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBorrowedGames(params?: FindAllBorrowedGames$Params, context?: HttpContext): Observable<PageResponseBorrowedGameResponse> {
    return this.findAllBorrowedGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBorrowedGameResponse>): PageResponseBorrowedGameResponse => r.body)
    );
  }

}
