/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findAllReviewsByGame } from '../fn/review/find-all-reviews-by-game';
import { FindAllReviewsByGame$Params } from '../fn/review/find-all-reviews-by-game';
import { PageResponseReviewResponse } from '../models/page-response-review-response';
import { saveFeedback } from '../fn/review/save-feedback';
import { SaveFeedback$Params } from '../fn/review/save-feedback';

@Injectable({ providedIn: 'root' })
export class ReviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveFeedback()` */
  static readonly SaveFeedbackPath = '/reviews';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFeedback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback$Response(params: SaveFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveFeedback(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFeedback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback(params: SaveFeedback$Params, context?: HttpContext): Observable<number> {
    return this.saveFeedback$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findAllReviewsByGame()` */
  static readonly FindAllReviewsByGamePath = '/reviews/game/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllReviewsByGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReviewsByGame$Response(params: FindAllReviewsByGame$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReviewResponse>> {
    return findAllReviewsByGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllReviewsByGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReviewsByGame(params: FindAllReviewsByGame$Params, context?: HttpContext): Observable<PageResponseReviewResponse> {
    return this.findAllReviewsByGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReviewResponse>): PageResponseReviewResponse => r.body)
    );
  }

}
