/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedGameResponse {
  description?: string;
  id?: number;
  publisher?: string;
  rate?: number;
  releaseDate?: string;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
