/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameRequest {
  description: string;
  id?: number;
  publisher: string;
  releaseDate: string;
  shareable?: boolean;
  title: string;
}
