/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameResponse {
  archived?: boolean;
  cover?: string;
  description?: string;
  id?: number;
  owner?: string;
  publisher?: string;
  rate?: number;
  releaseDate?: string;
  shareable?: boolean;
  title?: string;
}
