/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BorrowedGameResponse } from './models/borrowed-game-response';
export type { GameRequest } from './models/game-request';
export type { GameResponse } from './models/game-response';
export type { PageResponseBorrowedGameResponse } from './models/page-response-borrowed-game-response';
export type { PageResponseGameResponse } from './models/page-response-game-response';
export type { PageResponseReviewResponse } from './models/page-response-review-response';
export type { RegistrationRequest } from './models/registration-request';
export type { ReviewRequest } from './models/review-request';
export type { ReviewResponse } from './models/review-response';
