spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 60MB
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false

server:
  servlet:
    context-path: /api/v1/


