spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 60MB
  liquibase:
    enabled: false

springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false

server:
  servlet:
    context-path: /api/v1/


